// Launch identity is evidence, not a title/name heuristic. Shell-generated grouping
// keys are not explicit per-window AppUserModelIDs. All lookups remain local.
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using System.Windows.Forms;

namespace TaskbarTiles
{
    static class LaunchResolution
    {
        internal static bool ExplicitId(string id)
        {
            id = LaunchIdentity.CleanId(id);
            return id.Length > 0 && !LaunchIdentity.FullPath(id) &&
                !id.StartsWith("Microsoft.AutoGenerated.", StringComparison.OrdinalIgnoreCase);
        }
        internal static bool ProfileScoped(string id)
        {
            id = LaunchIdentity.CleanId(id);
            return id.StartsWith("Chrome.", StringComparison.OrdinalIgnoreCase) ||
                id.StartsWith("MSEdge.", StringComparison.OrdinalIgnoreCase) ||
                id.StartsWith("Brave.", StringComparison.OrdinalIgnoreCase);
        }
        internal static void ApplyShellMetadata(LaunchReceipt receipt, string id, string exe)
        {
            id = LaunchIdentity.CleanId(id);
            // Never replace a requested explicit profile identity with a different one.
            if (id.Length > 0 && !LaunchIdentity.ConflictingIds(receipt.ExpectedAppId, id))
                if (!ExplicitId(receipt.ExpectedAppId) || ExplicitId(id)) receipt.ExpectedAppId = id;
            exe = Environment.ExpandEnvironmentVariables((exe ?? "").Trim().Trim('"'));
            if (LaunchIdentity.FullPath(exe) && exe.EndsWith(".exe", StringComparison.OrdinalIgnoreCase))
                receipt.ExpectedExe = exe;
        }
        internal static void ResolveShellTarget(string target, LaunchReceipt receipt)
        {
            if (string.IsNullOrWhiteSpace(target)) return;
            // This is the exact item being launched, not an icon-only friendly-name match.
            string id = ShellIcons.FileProperty(target, "System.AppUserModel.ID");
            string exe = ShellIcons.FileProperty(target, "System.Link.TargetParsingPath");
            if (target.EndsWith(".lnk", StringComparison.OrdinalIgnoreCase) && string.IsNullOrWhiteSpace(exe))
                exe = ReadShortcutTarget(target);
            const string prefix = @"shell:AppsFolder\";
            if (target.StartsWith(prefix, StringComparison.OrdinalIgnoreCase) &&
                (!LaunchIdentity.FullPath(exe) || string.IsNullOrWhiteSpace(id)))
            {
                object shell = null, folder = null, item = null;
                try
                {
                    shell = Activator.CreateInstance(Type.GetTypeFromProgID("Shell.Application"));
                    dynamic api = shell; folder = api.NameSpace("shell:AppsFolder");
                    if (folder != null)
                    {
                        dynamic items = folder; item = items.ParseName(target.Substring(prefix.Length));
                        if (item != null)
                        {
                            dynamic exact = item;
                            if (string.IsNullOrWhiteSpace(id)) id = Convert.ToString(exact.ExtendedProperty("System.AppUserModel.ID"));
                            if (!LaunchIdentity.FullPath(exe)) exe = Convert.ToString(exact.ExtendedProperty("System.Link.TargetParsingPath"));
                        }
                    }
                }
                catch { }
                finally { Release(item); Release(folder); Release(shell); }
            }
            ApplyShellMetadata(receipt, id, exe);
        }
        static string ReadShortcutTarget(string target)
        {
            object shell = null, link = null;
            try
            {
                if (!File.Exists(target)) return "";
                shell = Activator.CreateInstance(Type.GetTypeFromProgID("WScript.Shell"));
                dynamic api = shell; link = api.CreateShortcut(target); dynamic shortcut = link;
                return Convert.ToString(shortcut.TargetPath) ?? "";
            }
            catch { return ""; }
            finally { Release(link); Release(shell); }
        }
        static void Release(object item)
        { if (item != null && Marshal.IsComObject(item)) Marshal.ReleaseComObject(item); }
        internal static string Describe(string id, string exe)
        {
            id = LaunchIdentity.CleanId(id);
            string kind = id.Length == 0 ? "absent" : LaunchIdentity.FullPath(id) ? "path" : ExplicitId(id) ? "explicit" : "generated";
            string fingerprint = "none";
            if (id.Length > 0)
                using (var sha = SHA256.Create())
                    fingerprint = BitConverter.ToString(sha.ComputeHash(Encoding.UTF8.GetBytes(id.ToUpperInvariant())), 0, 6).Replace("-", "").ToLowerInvariant();
            return "id-kind=" + kind + "; id-hash=" + fingerprint + "; exe=" + LaunchIdentity.Leaf(exe);
        }
        internal static string Reason(AppButton app, WindowRecord window, LaunchReceipt receipt)
        {
            string wanted = receipt != null && !string.IsNullOrWhiteSpace(receipt.ExpectedAppId) ? receipt.ExpectedAppId : app.AppId;
            if (window.IdentityAmbiguous) return "rejected: ambiguous hosted application";
            if (LaunchIdentity.ConflictingIds(wanted, window.AppId)) return "rejected: explicit app/profile ID conflict";
            if (LaunchIdentity.Matches(app, window, receipt)) return "identity matched";
            if (ProfileScoped(wanted)) return "waiting: explicit browser profile ID";
            return "unverified: insufficient executable/process/app identity";
        }
    }

    sealed class HostedIdentity
    {
        internal uint ProcessId;
        internal long Started;
        internal string AppId, Exe;
    }
    static class HostedWindowIdentity
    {
        internal static void Refresh(IntPtr window, WindowRecord entry)
        {
            // Inspect only this known shell frame host. Never select an arbitrary
            // child renderer of a normal desktop application as its owner.
            if (LaunchIdentity.Leaf(entry.Exe) != "applicationframehost.exe") return;
            var found = new List<HostedIdentity>(); var seen = new HashSet<uint>(); int visited = 0;
            Native.EnumChildWindows(window, delegate(IntPtr child, IntPtr unused)
            {
                if (++visited > 128) return false;
                if (Native.Class(child) != "Windows.UI.Core.CoreWindow") return true;
                uint pid = WindowNative.ProcessId(child);
                if (pid == 0 || pid == entry.ProcessId || !seen.Add(pid)) return true;
                string id = PackageIdentity.ForProcess(pid);
                if (!LaunchResolution.ExplicitId(id)) return true;
                found.Add(new HostedIdentity { ProcessId = pid, AppId = id,
                    Exe = ShellIcons.ProcessFile(child), Started = PackageIdentity.StartTicks(pid) });
                return true;
            }, IntPtr.Zero);
            Apply(entry, found);
        }
        internal static void Apply(WindowRecord owner, IList<HostedIdentity> children)
        {
            if (children.Count == 0) return;
            if (children.Count != 1 || LaunchIdentity.ConflictingIds(owner.AppId, children[0].AppId))
            { owner.IdentityAmbiguous = true; return; }
            HostedIdentity child = children[0];
            owner.AppProcessId = child.ProcessId; owner.AppProcessStartTicks = child.Started;
            if (!LaunchResolution.ExplicitId(owner.AppId)) owner.AppId = child.AppId;
            if (!string.IsNullOrWhiteSpace(child.Exe)) owner.Exe = child.Exe;
            // owner.Handle/ProcessId/ProcessStartTicks still describe the top-level
            // frame. The mover and manual chooser validate that owner, not the child.
        }
    }

    sealed partial class SettingsWindow
    {
        void AddUpdatesPage()
        {
            var page = Page("Updates");
            Section(page, "Updates from GitHub", "Installed version: " + Program.Version + ". Existing settings, favourites and X-Mouse commands are retained by Setup.");
            var check = Theme.Button("Check for updates...", 235);
            check.Click += delegate { using (var dialog = new UpdatesWindow(true)) dialog.ShowDialog(this); };
            Row(page, "Check and update", "Checks the latest published GitHub release. The next screen shows release notes and a Download & install button. Nothing installs silently.", check);
            var notes = Theme.Button("Open release notes", 235);
            notes.Click += delegate { try { ReleaseInfo.Open(ReleaseInfo.LatestUrl); } catch (Exception ex) { MessageBox.Show(this, ex.Message, "Release notes"); } };
            Row(page, "Release history", "Opens the project's public GitHub release page in your browser.", notes);
            Section(page, "Download verification", "The updater verifies SHA-256 before opening Setup. These builds are unsigned: the checksum detects corruption, not an independent publisher identity. No Git login or developer tools are required.");
        }
    }
}
