using System;
using System.Collections.Generic;
using System.Text;

namespace TaskbarTiles
{
    static class LaunchResolutionTests
    {
        static int count;
        static void Check(bool ok, string label)
        { count++; if (!ok) throw new InvalidOperationException("Launch resolution: " + label); }
        internal static void Run(StringBuilder log)
        {
            count = 0;
            const string exe = @"C:\Apps\Editor\editor.exe";
            var app = new AppButton { Id = "Appid:Microsoft.AutoGenerated.7A8B", LaunchExe = exe };
            var window = new WindowRecord { Handle = new IntPtr(24), ProcessId = 40, ProcessStartTicks = 900, Exe = exe, AppId = "Contoso.Editor" };
            Check(!LaunchResolution.ExplicitId(app.AppId), "generated grouping key is not an explicit window ID");
            Check(!LaunchResolution.ExplicitId(exe), "executable path is not an explicit ID");
            Check(LaunchResolution.ExplicitId("Chrome.Profile-A"), "profile ID remains explicit");
            Check(LaunchIdentity.Matches(app, window, null), "generated key with verified exact exe matches explicit window");
            window.Exe = @"C:\Other\editor.exe";
            Check(!LaunchIdentity.Matches(app, window, null), "same filename from other installation does not match");
            window.Exe = exe;
            app.LaunchExe = "";
            Check(!LaunchIdentity.Matches(app, window, null), "generated key alone cannot authorise a move");
            var receipt = new LaunchReceipt { ExpectedAppId = app.AppId };
            LaunchResolution.ApplyShellMetadata(receipt, "Contoso.Editor", exe);
            Check(receipt.ExpectedAppId == "Contoso.Editor" && receipt.ExpectedExe == exe, "exact shell item supplies canonical launch metadata");
            Check(LaunchIdentity.Matches(app, window, receipt), "resolved metadata works without returned PID");
            window.AppId = "Contoso.Other";
            Check(!LaunchIdentity.Matches(app, window, receipt), "conflicting explicit IDs remain blocked even with exact exe");
            receipt.ExpectedAppId = "Chrome.Profile-A";
            LaunchResolution.ApplyShellMetadata(receipt, "Chrome.Profile-B", exe);
            Check(receipt.ExpectedAppId == "Chrome.Profile-A", "shell metadata cannot replace explicit profile");
            window.AppId = "";
            receipt.ProcessId = 40; receipt.ProcessStartTicks = 900;
            Check(!LaunchIdentity.Matches(app, window, receipt), "missing profile ID cannot be bypassed by PID or exe");
            window.AppId = "Chrome.Profile-A";
            Check(LaunchIdentity.Matches(app, window, receipt), "correct profile is allowed");
            receipt.ExpectedAppId = "Microsoft.AutoGenerated.7A8B"; receipt.ExpectedExe = "";
            window.AppId = "Contoso.Editor";
            Check(LaunchIdentity.Matches(app, window, receipt), "returned non-host PID can bridge generated key");
            receipt.ProcessStartTicks = 901;
            Check(!LaunchIdentity.Matches(app, window, receipt), "recycled process cannot bridge identity");
            receipt.ProcessStartTicks = 900; window.Exe = @"C:\Windows\explorer.exe";
            Check(!LaunchIdentity.Matches(app, window, receipt), "shell broker is not app PID evidence");

            var owner = new WindowRecord { Handle = new IntPtr(60), ProcessId = 80, ProcessStartTicks = 100, Exe = @"C:\Windows\System32\ApplicationFrameHost.exe", AppId = "" };
            var child = new HostedIdentity { ProcessId = 81, Started = 101, Exe = exe, AppId = "Contoso.Packaged!App" };
            HostedWindowIdentity.Apply(owner, new List<HostedIdentity> { child });
            Check(owner.ProcessId == 80 && owner.ProcessStartTicks == 100 && owner.Handle == new IntPtr(60), "frame owner validation identity is preserved");
            Check(owner.AppProcessId == 81 && owner.AppProcessStartTicks == 101, "hosted app PID/start stored separately");
            Check(owner.AppId == child.AppId && owner.Exe == exe, "hosted package metadata resolves top-level frame");
            receipt = new LaunchReceipt { ExpectedAppId = child.AppId };
            Check(LaunchIdentity.Matches(app, owner, receipt), "hosted packaged app matches with pid zero receipt");
            HostedWindowIdentity.Apply(owner, new List<HostedIdentity> { child, new HostedIdentity { ProcessId = 82, AppId = "Contoso.Other!App" } });
            Check(owner.IdentityAmbiguous && !LaunchIdentity.Matches(app, owner, receipt), "multiple hosted app identities are never guessed");
            owner.IdentityAmbiguous = false; owner.AppId = "Contoso.Other!App";
            HostedWindowIdentity.Apply(owner, new List<HostedIdentity> { child });
            Check(owner.IdentityAmbiguous, "conflicting frame and child explicit identity rejected");

            var baseline = new Dictionary<IntPtr, uint> { { new IntPtr(60), 80 } };
            owner.IdentityAmbiguous = false; owner.AppId = child.AppId;
            Check(!LaunchIdentity.IsNew(owner, baseline) && LaunchIdentity.Matches(app, owner, receipt), "reused matching frame remains eligible existing candidate");
            Check(!LaunchIdentity.CanReuse(true, true, 20, 15, false, true, 1000), "explicit new-window request still cannot reuse old frame");
            string description = LaunchResolution.Describe("Private.Profile-Name", @"C:\Users\private-name\editor.exe");
            Check(!description.Contains("Private.Profile") && !description.Contains("Users") && description.Contains("editor.exe"), "diagnostics omit raw identities and user path");
            Check(description == LaunchResolution.Describe("private.profile-name", @"C:\Other\editor.exe"), "normalised fingerprints support correlation");
            log.AppendLine("PASS: " + count + " generated/explicit identity, profile safety, hosted-frame and diagnostics regression assertions. Native Shell lookup and live app placement require desktop testing.");
        }
    }
}
