package main

import("context";"encoding/json";"errors";"os";"path/filepath";"strings";"time")
type sdkEvent struct{Event string `json:"event"`;Action string `json:"action"`;Context string `json:"context"`;Device string `json:"device"`;Payload json.RawMessage `json:"payload"`}
type status struct{Version string `json:"version"`;Config PublicConfig `json:"config"`;Phase string `json:"phase"`;Message string `json:"message"`;Count *int64 `json:"count"`;LastSuccess *CountReading `json:"lastSuccess,omitempty"`;TestedStore *CountReading `json:"testedStore,omitempty"`;Stores []Store `json:"stores"`;Busy bool `json:"busy"`;VisibleInstances int `json:"visibleInstances"`;NextCheck time.Time `json:"nextCheck"`;PollSeconds int `json:"pollSeconds"`}
type jobResult struct{Generation uint64;Kind string;Reading *CountReading;Stores []Store;Err error;Started time.Time}
type worker interface{Execute(context.Context,Config,string)(*CountReading,[]Store,error);Close()}
type remoteWorker struct{client *mcpClient;key string}
func(r *remoteWorker)Close(){if r.client!=nil{r.client.close()}}
func(r *remoteWorker)Execute(ctx context.Context,c Config,kind string)(*CountReading,[]Store,error){token,e:=tokenFor(c);if e!=nil{return nil,nil,e};key:=c.Endpoint+"\x00"+token;if r.client==nil||r.key!=key{r.Close();r.client=newMCP(c.Endpoint,token);r.key=key};if kind=="sites"{v,e:=r.client.call(ctx,SitesTool,map[string]any{"limit":1000});if e!=nil{return nil,nil,e};s,e:=parseSites(v);return nil,s,e};args:=map[string]any{};if c.BlogID>0{args["blog_id"]=c.BlogID};v,e:=r.client.call(ctx,SnapshotTool,args);if e!=nil{return nil,nil,e};reading,e:=parseCount(v,c,time.Now());if e!=nil{return nil,nil,e};return &reading,nil,nil}
type app struct{config Config;configPath string;art *Artwork;send func(any)error;log func(string);now func()time.Time;contexts map[string]string;inspectors map[string]bool;sent map[string]string;busy bool;generation uint64;pending string;cancel context.CancelFunc;done chan jobResult;remote worker;count *int64;last *CountReading;tested *CountReading;stores []Store;phase,message string;nextDue,lastManual time.Time;failures int;imageKey,imageData string}
func newApp(c Config,path string,art *Artwork,send func(any)error,w worker)*app{return &app{config:c,configPath:path,art:art,send:send,log:logger,now:time.Now,contexts:map[string]string{},inspectors:map[string]bool{},sent:map[string]string{},done:make(chan jobResult,1),remote:w,phase:"setup",message:"Enter your existing MCP connection, test it, and confirm the store.",stores:[]Store{}}}
func(a *app)report()status{return status{Version,a.config.public(),a.phase,a.message,a.count,a.last,a.tested,a.stores,a.busy,len(a.contexts),a.nextDue,300}}
func(a *app)persistStatus(){b,e:=json.MarshalIndent(a.report(),"","  ");if e==nil{dir:=filepath.Dir(a.configPath);_=os.MkdirAll(dir,0700);_=os.WriteFile(filepath.Join(dir,"status.json"),b,0600)}}
func(a *app)sendStatus(ctx string){_=a.send(map[string]any{"event":"sendToPropertyInspector","action":ActionID,"context":ctx,"payload":a.report()})}
func(a *app)update(){key:=viewKey(a.count);if a.imageData==""||a.imageKey!=key{b,e:=a.art.render(a.count);if e!=nil{a.log("Artwork rendering failed.");return};a.imageData=imageURI(b);a.imageKey=key};for ctx:=range a.contexts{if a.sent[ctx]!=key{if e:=a.send(map[string]any{"event":"setImage","context":ctx,"payload":map[string]any{"image":a.imageData,"target":0}});e==nil{a.sent[ctx]=key}}};for ctx:=range a.inspectors{a.sendStatus(ctx)};a.persistStatus()}
func(a *app)stop(){if a.cancel!=nil{a.cancel()};a.pending=""}
func(a *app)request(kind string,manual bool){if manual{if !a.lastManual.IsZero()&&a.now().Sub(a.lastManual)<5*time.Second{a.message="Please wait a few seconds before another manual check.";return};a.lastManual=a.now()};a.pending=kind;a.startPending()}
func(a *app)startPending(){if a.busy||a.pending==""{return};kind:=a.pending;a.pending="";if kind=="poll"&&(len(a.contexts)==0||!a.config.Confirmed){return};a.busy=true;started:=a.now();a.nextDue=started.Add(PollInterval);a.phase="checking";a.message="Reading processing-order counts. No order or customer records are requested.";if kind=="sites"{a.message="Reading your multisite store list (no customer data)."};ctx,cancel:=context.WithTimeout(context.Background(),60*time.Second);a.cancel=cancel;cfg:=a.config;gen:=a.generation;go func(){defer cancel();r,s,e:=a.remote.Execute(ctx,cfg,kind);a.done<-jobResult{gen,kind,r,s,e,started}}()}
func(a *app)complete(j jobResult){a.busy=false;a.cancel=nil;if j.Generation!=a.generation{a.startPending();a.update();return};if errors.Is(j.Err,context.Canceled){a.phase="hidden";a.message="Monitoring stopped because the display is hidden.";a.startPending();a.update();return};if j.Err!=nil{a.count=nil;a.tested=nil;a.failures++;a.nextDue=a.now().Add(failureDelay(a.failures));a.phase="unavailable";if errors.Is(j.Err,context.DeadlineExceeded){a.message="The request timed out. Automatic retries slow down after failures."}else{a.message=j.Err.Error()};a.log("Check failed: "+a.message)}else if j.Kind=="sites"{a.stores=j.Stores;a.phase="setup";a.message="Select the store to monitor, then Save and test. Only that store will be counted.";a.failures=0}else if j.Reading!=nil{a.failures=0;a.nextDue=a.now().Add(PollInterval);if j.Kind=="test"||!a.config.Confirmed{a.tested=j.Reading;a.count=nil;a.phase="confirm";a.message="Connection works. Check the store URL and count below, then click Use this store."}else{n:=j.Reading.Count;a.count=&n;a.last=j.Reading;a.phase="online";a.message="Confirmed processing orders from the selected store. Next automatic check in five minutes."};a.log("Count check completed successfully.")};a.startPending();a.update()}
func(a *app)tick(){if len(a.contexts)==0||!a.config.Confirmed||a.busy{return};if a.nextDue.IsZero()||!a.now().Before(a.nextDue){if a.last==nil||a.now().Sub(a.last.CheckedAt)>PollInterval+time.Minute{a.count=nil};a.request("poll",false);a.update()}}
func(a *app)waitDuration()(time.Duration,bool){if a.busy||len(a.contexts)==0||!a.config.Confirmed{return 0,false};if a.nextDue.IsZero(){return 0,true};return max(0,a.nextDue.Sub(a.now())),true}
func(a *app)saveInput(raw json.RawMessage,kind string)error{var in struct{Config struct{Endpoint string `json:"endpoint"`;BlogID int64 `json:"blogID"`;UseEnvironment bool `json:"useEnvironment"`} `json:"config"`;Token string `json:"token"`};if json.Unmarshal(raw,&in)!=nil{return errors.New("Invalid settings message.")};endpoint,e:=validateEndpoint(in.Config.Endpoint);if e!=nil{return e};if in.Config.BlogID<0{return errors.New("Blog ID cannot be negative.")};if e=validateToken(in.Token);e!=nil{return e};c:=a.config;c.Endpoint=endpoint;c.BlogID=in.Config.BlogID;c.Confirmed=false;c.SiteURL="";c.UseEnvironment=in.Config.UseEnvironment;if endpoint!=a.config.Endpoint{c.ProtectedToken=""};if t:=strings.TrimSpace(in.Token);t!=""{if strings.HasPrefix(strings.ToLower(t),"bearer "){t=strings.TrimSpace(t[7:])};c.ProtectedToken,e=protectSecret(t);if e!=nil{return e};c.UseEnvironment=false};if c.UseEnvironment{c.ProtectedToken=""};if _,e=tokenFor(c);e!=nil{return e};if e=saveConfig(a.configPath,c);e!=nil{return errors.New("Could not save settings locally. Check the Windows user's AppData permissions.")};a.config=c;a.generation++;if a.cancel!=nil{a.cancel()};a.tested=nil;a.count=nil;a.last=nil;a.nextDue=time.Time{};a.failures=0;a.sent=map[string]string{};a.pending=kind;a.startPending();return nil}
func(a *app)confirm()error{if a.tested==nil||a.busy{return errors.New("Run Save and test, then confirm the returned store.")};if a.now().Sub(a.tested.CheckedAt)>10*time.Minute{return errors.New("The setup test is too old. Run Save and test again.")};c:=a.config;c.BlogID=a.tested.Store.BlogID;c.SiteURL=a.tested.Store.URL;c.Confirmed=true;if e:=saveConfig(a.configPath,c);e!=nil{return errors.New("Could not save the store confirmation.")};a.config=c;n:=a.tested.Count;a.count=&n;a.last=a.tested;a.tested=nil;a.phase="online";a.message="Store confirmed. Five-minute monitoring starts only when this display is visible.";a.nextDue=a.now().Add(PollInterval);return nil}
func(a *app)handle(ev sdkEvent){if ev.Action!=""&&ev.Action!=ActionID{return};switch ev.Event{
case "willAppear":if ev.Context==""||len(a.contexts)>=64{return};a.contexts[ev.Context]=ev.Device;delete(a.sent,ev.Context);a.tick()
case "willDisappear":delete(a.contexts,ev.Context);delete(a.sent,ev.Context);delete(a.inspectors,ev.Context);if len(a.contexts)==0{a.stop();a.phase="hidden";a.message="No automatic requests while the display is hidden."}
case "deviceDidDisconnect":for ctx,dev:=range a.contexts{if dev==ev.Device{delete(a.contexts,ctx);delete(a.sent,ctx);delete(a.inspectors,ctx)}};if len(a.contexts)==0{a.stop()}
case "systemDidWakeUp":if a.last==nil||a.now().Sub(a.last.CheckedAt)>PollInterval+time.Minute{a.count=nil};a.tick()
case "propertyInspectorDidAppear":if ev.Context!=""&&(len(a.inspectors)<64||a.inspectors[ev.Context]){a.inspectors[ev.Context]=true}
case "propertyInspectorDidDisappear":delete(a.inspectors,ev.Context)
case "sendToPlugin":if ev.Context==""{return};if len(a.inspectors)<64||a.inspectors[ev.Context]{a.inspectors[ev.Context]=true};var p struct{Op string `json:"op"`};if json.Unmarshal(ev.Payload,&p)!=nil{return};var e error;switch p.Op{case "getStatus":case "save_test":e=a.saveInput(ev.Payload,"test");case "load_stores":e=a.saveInput(ev.Payload,"sites");case "confirm":e=a.confirm();case "refresh":if !a.config.Confirmed{e=errors.New("Test and confirm a store before refreshing.")}else if !a.busy{a.request("refresh",true)};case "forget_token":a.stop();a.generation++;a.config.ProtectedToken="";a.config.UseEnvironment=false;a.config.Confirmed=false;a.count=nil;a.tested=nil;e=saveConfig(a.configPath,a.config);a.phase="setup";a.message="Saved token removed. The environment variable itself was not changed.";default:return};if e!=nil{a.message=e.Error();if !a.config.Confirmed{a.phase="setup"}}
default:return};a.update()}
func runPlugin(port int,uuid,register,root,path string)error{if register!="registerPlugin"{return errors.New("Unexpected SDK registration event.")};art,e:=loadArt(root);if e!=nil{return e};c,e:=readConfig(path);note:="";if e!=nil{note=e.Error();c=defaults()};sock,e:=connectSocket(port);if e!=nil{return e};defer sock.close();send:=func(v any)error{b,e:=json.Marshal(v);if e!=nil{return e};return sock.sendText(b)};if e=send(map[string]any{"event":register,"uuid":uuid});e!=nil{return e};a:=newApp(c,path,art,send,&remoteWorker{});if note!=""{a.message=note};defer a.stop();incoming:=make(chan sdkEvent,16);errs:=make(chan error,1);quit:=make(chan struct{});defer close(quit);go func(){for{b,e:=sock.receive();if e!=nil{errs<-e;return};var ev sdkEvent;if json.Unmarshal(b,&ev)!=nil{continue};select{case incoming<-ev:case <-quit:return}}}();a.log("Plugin started; no automatic network requests until a confirmed display is visible.");for{var timer *time.Timer;var tc <-chan time.Time;if d,ok:=a.waitDuration();ok{timer=time.NewTimer(d);tc=timer.C};select{case ev:=<-incoming:a.handle(ev);case j:=<-a.done:a.complete(j);case <-tc:a.tick();case e:=<-errs:if timer!=nil{timer.Stop()};return e};if timer!=nil{timer.Stop()}}}
