package main
import("context";"errors";"path/filepath";"sync/atomic";"testing";"time")
type fakeWorker struct{n atomic.Int32;hold bool}
func(f *fakeWorker)Close(){}
func(f *fakeWorker)Execute(ctx context.Context,c Config,k string)(*CountReading,[]Store,error){f.n.Add(1);if f.hold{<-ctx.Done();return nil,nil,ctx.Err()};return &CountReading{7,Store{1,"https://shop.test"},time.Now()},nil,nil}
func testApp(t *testing.T,w worker)(*app,*[]map[string]any){t.Helper();art,_:=loadArt("");out:=[]map[string]any{};c:=Config{Endpoint:DefaultEndpoint,BlogID:1,SiteURL:"https://shop.test",Confirmed:true};a:=newApp(c,filepath.Join(t.TempDir(),"settings.json"),art,func(v any)error{out=append(out,v.(map[string]any));return nil},w);a.log=func(string){};return a,&out}
func completeJob(t *testing.T,a *app){t.Helper();select{case j:=<-a.done:a.complete(j);case <-time.After(2*time.Second):t.Fatal("worker timeout")}}
func imageCount(out []map[string]any)int{n:=0;for _,v:=range out{if v["event"]=="setImage"{n++}};return n}
func TestVisibleOnly(t *testing.T){w:=&fakeWorker{};a,out:=testApp(t,w);a.tick();if a.busy{t.Fatal("hidden request")};a.handle(sdkEvent{Event:"willAppear",Action:ActionID,Context:"one",Device:"d"});completeJob(t,a);if w.n.Load()!=1||a.count==nil||*a.count!=7{t.Fatal("no count")};n:=imageCount(*out);a.update();if imageCount(*out)!=n{t.Fatal("unchanged repaint")};a.tick();if a.busy{t.Fatal("early polling")};a.handle(sdkEvent{Event:"willDisappear",Context:"one"});if _,ok:=a.waitDuration();ok{t.Fatal("hidden timer")}}
func TestLastHiddenCancels(t *testing.T){w:=&fakeWorker{hold:true};a,_:=testApp(t,w);a.handle(sdkEvent{Event:"willAppear",Context:"one"});a.handle(sdkEvent{Event:"willAppear",Context:"two"});a.handle(sdkEvent{Event:"willDisappear",Context:"one"});if !a.busy{t.Fatal("early stop")};a.handle(sdkEvent{Event:"willDisappear",Context:"two"});completeJob(t,a);if a.busy||w.n.Load()!=1{t.Fatal("not stopped")}}
func TestDeviceCancellation(t *testing.T){w:=&fakeWorker{hold:true};a,_:=testApp(t,w);a.handle(sdkEvent{Event:"willAppear",Context:"one",Device:"d"});a.handle(sdkEvent{Event:"deviceDidDisconnect",Device:"d"});completeJob(t,a);if a.busy||len(a.contexts)!=0{t.Fatal("still active")}}
func TestErrorIsUnknown(t *testing.T){a,_:=testApp(t,&fakeWorker{});n:=int64(7);a.count=&n;a.busy=true;a.complete(jobResult{Kind:"poll",Err:errors.New("synthetic")});if a.count!=nil||a.phase!="unavailable"{t.Fatal("false zero")};if a.nextDue.Sub(a.now())<4*time.Minute{t.Fatal("rapid retry")}}
func TestPinStoreConfirmation(t *testing.T){a,_:=testApp(t,&fakeWorker{});a.config.Confirmed=false;a.tested=&CountReading{0,Store{6,"https://camp.test"},time.Now()};if e:=a.confirm();e!=nil{t.Fatal(e)};c,e:=readConfig(a.configPath);if e!=nil||!c.Confirmed||c.BlogID!=6||a.count==nil||*a.count!=0{t.Fatal(c,e)}}
func TestObsoleteResultDiscarded(t *testing.T){a,_:=testApp(t,&fakeWorker{});a.generation=2;a.busy=true;a.complete(jobResult{Generation:1,Kind:"poll",Reading:&CountReading{7,Store{1,"https://shop.test"},time.Now()}});if a.count!=nil||a.last!=nil{t.Fatal("stale result applied")}}
