package main
import("bufio";"bytes";"context";"encoding/json";"errors";"fmt";"io";"net/http";"strconv";"strings";"time")
type rpcResponse struct{JSONRPC string `json:"jsonrpc"`;ID json.RawMessage `json:"id"`;Result json.RawMessage `json:"result"`;Error *struct{Code int `json:"code"`;Message string `json:"message"`} `json:"error"`}
type mcpClient struct{endpoint,token,session,protocol string;initialized bool;nextID int64;http *http.Client}
func newMCP(endpoint,token string)*mcpClient{t:=http.DefaultTransport.(*http.Transport).Clone();t.MaxIdleConns=2;t.MaxIdleConnsPerHost=1;t.MaxConnsPerHost=1;t.IdleConnTimeout=90*time.Second;t.ResponseHeaderTimeout=15*time.Second;t.TLSHandshakeTimeout=10*time.Second;return &mcpClient{endpoint:endpoint,token:token,protocol:"2025-06-18",http:&http.Client{Transport:t,Timeout:25*time.Second,CheckRedirect:func(req *http.Request,via []*http.Request)error{return errors.New("Redirect refused; configure the final MCP URL so credentials are not forwarded.")}}}}
func(c *mcpClient)close(){c.http.CloseIdleConnections()}
func idMatches(b json.RawMessage,id int64)bool{var n json.Number;if json.Unmarshal(b,&n)==nil{return string(n)==strconv.FormatInt(id,10)};return false}
func parseRPC(b []byte,id int64)(any,error){var r rpcResponse;if len(b)>MaxResponse||json.Unmarshal(b,&r)!=nil{return nil,errors.New("Invalid MCP JSON-RPC response.")};if !idMatches(r.ID,id){return nil,errors.New("MCP response ID mismatch.")};if r.Error!=nil{switch r.Error.Code{case -32601:return nil,errors.New("MCP tool/method not found. Check StoreOps is enabled.");case -32602:return nil,errors.New("MCP rejected arguments. Check blog ID.");default:return nil,fmt.Errorf("MCP error code %d; raw server text not logged.",r.Error.Code)}};if len(r.Result)==0{return nil,errors.New("MCP result missing.")};return decodeJSON(r.Result)}
func readSSE(r io.Reader,id int64)(any,error){
 sc:=bufio.NewScanner(io.LimitReader(r,MaxResponse+1));sc.Buffer(make([]byte,4096),MaxResponse);var event strings.Builder;read:=0
 flush:=func()(any,bool,error){if event.Len()==0{return nil,false,nil};data:=strings.TrimSpace(event.String());event.Reset();var envelope rpcResponse;if json.Unmarshal([]byte(data),&envelope)!=nil{return nil,false,errors.New("Invalid MCP event JSON.")};if !idMatches(envelope.ID,id){return nil,false,nil};v,e:=parseRPC([]byte(data),id);return v,true,e}
 for sc.Scan(){line:=sc.Text();read+=len(line)+1;if read>MaxResponse{return nil,errors.New("MCP stream size limit exceeded.")};if line==""{v,ok,e:=flush();if e!=nil||ok{return v,e};continue};if strings.HasPrefix(line,"data:"){event.WriteString(strings.TrimPrefix(strings.TrimPrefix(line,"data:")," "));event.WriteByte('\n')}}
 if e:=sc.Err();e!=nil{return nil,errors.New("MCP stream stopped before result.")};if v,ok,e:=flush();ok||e!=nil{return v,e};return nil,errors.New("MCP stream ended without matching result.")
}
var errExpiredSession=errors.New("MCP session expired")
func(c *mcpClient)post(ctx context.Context,method string,params any,notification bool)(any,error){
 if _,e:=validateEndpoint(c.endpoint);e!=nil{return nil,e};if e:=validateToken(c.token);e!=nil{return nil,e};c.nextID++;id:=c.nextID;message:=map[string]any{"jsonrpc":"2.0","method":method};if !notification{message["id"]=id};if params!=nil{message["params"]=params};body,e:=json.Marshal(message);if e!=nil{return nil,e}
 req,e:=http.NewRequestWithContext(ctx,http.MethodPost,c.endpoint,bytes.NewReader(body));if e!=nil{return nil,errors.New("Invalid MCP endpoint.")};req.Header.Set("Content-Type","application/json");req.Header.Set("Accept","application/json, text/event-stream");req.Header.Set("User-Agent","FoughtApple-NickNacksOrders/"+Version);if c.token!=""{req.Header.Set("Authorization","Bearer "+c.token)};if c.session!=""{req.Header.Set("Mcp-Session-Id",c.session)};if c.initialized{req.Header.Set("MCP-Protocol-Version",c.protocol)}
 resp,e:=c.http.Do(req);if e!=nil{if ctx.Err()!=nil{return nil,ctx.Err()};return nil,errors.New("Could not reach MCP securely within timeout. Check URL, TLS and gateway.")};defer resp.Body.Close();if resp.StatusCode==404&&c.session!=""{return nil,errExpiredSession}
 if resp.StatusCode<200||resp.StatusCode>=300{switch resp.StatusCode{case 401,403:return nil,errors.New("MCP access denied (401/403). Check bearer token and read-only tool permission.");case 404:return nil,errors.New("MCP endpoint not found (404).");case 405:return nil,errors.New("Use the Streamable HTTP endpoint, not legacy SSE or stdio.");case 429:return nil,errors.New("MCP rate limit (429); retries will slow down.");default:return nil,fmt.Errorf("MCP HTTP %d. Count not accepted.",resp.StatusCode)}}
 if s:=resp.Header.Get("Mcp-Session-Id");s!=""{if len(s)>1024||strings.ContainsAny(s,"\r\n"){return nil,errors.New("Invalid MCP session ID.")};c.session=s};if notification{return nil,nil}
 ct:=strings.ToLower(resp.Header.Get("Content-Type"));if strings.Contains(ct,"text/event-stream"){return readSSE(resp.Body,id)};b,e:=io.ReadAll(io.LimitReader(resp.Body,MaxResponse+1));if e!=nil{return nil,errors.New("Could not read MCP response.")};if len(b)>MaxResponse{return nil,errors.New("MCP response too large.")};if strings.Contains(ct,"text/html"){return nil,errors.New("URL returned a web page, not MCP. Check endpoint/login challenge.")};return parseRPC(b,id)
}
func(c *mcpClient)initialize(ctx context.Context)error{c.initialized=false;c.session="";v,e:=c.post(ctx,"initialize",map[string]any{"protocolVersion":"2025-06-18","capabilities":map[string]any{},"clientInfo":map[string]any{"name":"nicknacks-orders-display","version":Version}},false);if e!=nil{return e};m,ok:=v.(map[string]any);if !ok{return errors.New("Invalid MCP initialization.")};ver,_:=m["protocolVersion"].(string);switch ver{case "2024-11-05","2025-03-26","2025-06-18","2025-11-25":c.protocol=ver;default:return errors.New("Unsupported MCP protocol version.")};c.initialized=true;if _,e=c.post(ctx,"notifications/initialized",nil,true);e!=nil{c.initialized=false;return e};return nil}
func(c *mcpClient)call(ctx context.Context,tool string,args map[string]any)(any,error){
 if tool!=SnapshotTool&&tool!=SitesTool{return nil,errors.New("Only the two read-only NickNacks snapshot tools are allowed.")};for k:=range args{if tool==SnapshotTool&&k!="blog_id"{return nil,errors.New("Unexpected snapshot argument.")};if tool==SitesTool&&k!="limit"{return nil,errors.New("Unexpected site-list argument.")}}
 if !c.initialized{if e:=c.initialize(ctx);e!=nil{return nil,e}};v,e:=c.post(ctx,"tools/call",map[string]any{"name":tool,"arguments":args},false);if errors.Is(e,errExpiredSession){if e=c.initialize(ctx);e!=nil{return nil,e};return c.post(ctx,"tools/call",map[string]any{"name":tool,"arguments":args},false)};return v,e
}
