package main
import("encoding/json";"os";"path/filepath";"strings";"testing";"time")
func fixture(count,status string)string{return `{"success":true,"data":{"context":{"blog_id":1,"site_url":"https://shop.test"},"woocommerce_active":true,"order_counts":[{"status":"`+status+`","count":`+count+`}]}}`}
func parsed(t *testing.T,s string)any{t.Helper();v,e:=decodeJSON([]byte(s));if e!=nil{t.Fatal(e)};return v}
func TestCountValues(t *testing.T){for _,x:=range []struct{label,v string;ok bool;n int64}{{"positive","7",true,7},{"zero","0",true,0},{"string_zero",`"0"`,true,0},{"null","null",false,0},{"negative","-1",false,0},{"decimal","1.5",false,0},{"true","true",false,0},{"invalid_string",`"no"`,false,0},{"large","1234567",true,1234567}}{t.Run(x.label,func(t *testing.T){r,e:=parseCount(parsed(t,fixture(x.v,"wc-processing")),Config{},time.Now());if(e==nil)!=x.ok{t.Fatal(e)};if x.ok&&r.Count!=x.n{t.Fatal(r)}})}}
func TestResultWrappers(t *testing.T){f:=parsed(t,fixture("12","processing"));s:=fixture("12","processing");for n,v:=range map[string]any{"plain":f,"structured":map[string]any{"structuredContent":f},"content":map[string]any{"content":[]any{map[string]any{"type":"text","text":s}}},"result":map[string]any{"result":f},"encoded":s}{t.Run(n,func(t *testing.T){r,e:=parseCount(v,Config{},time.Now());if e!=nil||r.Count!=12{t.Fatal(r,e)}})}}
func TestRejectMissingAmbiguousOrWrongStore(t *testing.T){for name,v:=range map[string]any{"missing":parsed(t,fixture("6","wc-completed")),"tool_error":map[string]any{"isError":true,"content":[]any{}},"success_false":map[string]any{"success":false,"data":parsed(t,fixture("8","wc-processing"))},"inactive":map[string]any{"woocommerce_active":false},"duplicate":parsed(t,strings.Replace(fixture("7","wc-processing"),`"count":7}]`,`"count":7},{"status":"processing","count":7}]`,1)),"customer_object":map[string]any{"order_id":7,"total":0}}{t.Run(name,func(t *testing.T){if _,e:=parseCount(v,Config{},time.Now());e==nil{t.Fatal("accepted")}})};for _,c:=range []Config{{BlogID:2},{Confirmed:true,BlogID:1,SiteURL:"https://other.test"}}{if _,e:=parseCount(parsed(t,fixture("0","wc-processing")),c,time.Now());e==nil{t.Fatal("wrong store")}}}
func TestEndpoints(t *testing.T){for _,s:=range []string{"https://shop.test/wp-json/mcp/v1/http","http://127.0.0.1:8788/mcp","http://localhost/mcp","http://[::1]:1234/mcp"}{if _,e:=validateEndpoint(s);e!=nil{t.Fatal(s,e)}};for _,s:=range []string{"http://shop.test/mcp","file:///c:/secret","https://user:pass@shop.test/mcp","https://shop.test/mcp?token=x","https://shop.test/mcp#xx","not-a-url","https://shop.test:99999/mcp"}{if _,e:=validateEndpoint(s);e==nil{t.Fatal("unsafe",s)}}}
func TestStrictJSON(t *testing.T){for _,s:=range []string{`{} {}`,`{} garbage`,`x`,strings.Repeat(" ",MaxResponse+1)}{if _,e:=decodeJSON([]byte(s));e==nil{t.Fatal("accepted")}}}
func TestSites(t *testing.T){r,e:=parseSites(parsed(t,`{"success":true,"data":{"sites":[{"blog_id":1,"site_url":"https://shop.test"},{"blog_id":2,"site_url":"https://camp.test","archived":true}]}}`));if e!=nil||len(r)!=1||r[0].BlogID!=1{t.Fatal(r,e)};r,e=parseSites(parsed(t,`{"current_site":{"blog_id":1,"site_url":"https://shop.test"}}`));if e!=nil||len(r)!=1{t.Fatal(r,e)}}
func TestSettingsAndPrivacy(t *testing.T){t.Setenv("NICKNACKSAU_MCP_TOKEN","dummy-local-test-token");c:=Config{Endpoint:DefaultEndpoint,BlogID:3,ProtectedToken:"encrypted-sentinel",Confirmed:true,SiteURL:"https://shop.test",UseEnvironment:true};p:=filepath.Join(t.TempDir(),"settings.json");if e:=saveConfig(p,c);e!=nil{t.Fatal(e)};r,e:=readConfig(p);if e!=nil||r!=c{t.Fatal(r,e)};b,_:=json.Marshal(c.public());if strings.Contains(string(b),"sentinel")||strings.Contains(string(b),"dummy-local-test-token"){t.Fatal("secret leaked")};if e:=os.WriteFile(p,[]byte("broken"),0600);e!=nil{t.Fatal(e)};if _,e=readConfig(p);e==nil{t.Fatal("bad settings accepted")}}
func TestBackoff(t *testing.T){for i,w:=range []time.Duration{5,10,20,30,30}{if failureDelay(i+1)!=w*time.Minute{t.Fatal(i)}}}
func TestTokenInjection(t *testing.T){if validateToken("x\r\nother: value")==nil{t.Fatal("accepted")}}
